<?php

namespace Container0n6lWch;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsulterFicheFraisControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ConsulterFicheFraisController' shared autowired service.
     *
     * @return \App\Controller\ConsulterFicheFraisController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ConsulterFicheFraisController.php';

        $container->services['App\\Controller\\ConsulterFicheFraisController'] = $instance = new \App\Controller\ConsulterFicheFraisController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\ConsulterFicheFraisController', $container));

        return $instance;
    }
}
