<?php

namespace ContainerWBVaaRN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFichefraisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.snGbxDq.App\Entity\Fichefrais' shared service.
     *
     * @return \App\Entity\Fichefrais
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.snGbxDq": it references class "App\\Entity\\Fichefrais" but no such service exists.');
    }
}
