<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWBVaaRN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWBVaaRN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWBVaaRN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWBVaaRN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWBVaaRN\App_KernelDevDebugContainer([
    'container.build_hash' => 'WBVaaRN',
    'container.build_id' => 'f93159c8',
    'container.build_time' => 1638974332,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWBVaaRN');
