<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'consulter_fiche_frais' => [[], ['_controller' => 'App\\Controller\\ConsulterFicheFraisController::index'], [], [['text', '/consulter/fiche/frais']], [], []],
    'fichefrais_index' => [[], ['_controller' => 'App\\Controller\\FichefraisController::index'], [], [['text', '/fichefrais/']], [], []],
    'fichefrais_new' => [[], ['_controller' => 'App\\Controller\\FichefraisController::new'], [], [['text', '/fichefrais/new']], [], []],
    'fichefrais_show' => [['mois'], ['_controller' => 'App\\Controller\\FichefraisController::show'], [], [['variable', '/', '[^/]++', 'mois', true], ['text', '/fichefrais']], [], []],
    'fichefrais_edit' => [['mois'], ['_controller' => 'App\\Controller\\FichefraisController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'mois', true], ['text', '/fichefrais']], [], []],
    'fichefrais_delete' => [['mois'], ['_controller' => 'App\\Controller\\FichefraisController::delete'], [], [['variable', '/', '[^/]++', 'mois', true], ['text', '/fichefrais']], [], []],
    'visiteur_index' => [[], ['_controller' => 'App\\Controller\\VisiteurController::index'], [], [['text', '/visiteur/']], [], []],
    'visiteur_new' => [[], ['_controller' => 'App\\Controller\\VisiteurController::new'], [], [['text', '/visiteur/new']], [], []],
    'visiteur_show' => [['id'], ['_controller' => 'App\\Controller\\VisiteurController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/visiteur']], [], []],
    'visiteur_edit' => [['id'], ['_controller' => 'App\\Controller\\VisiteurController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/visiteur']], [], []],
    'visiteur_delete' => [['id'], ['_controller' => 'App\\Controller\\VisiteurController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/visiteur']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], []],
    'connexion' => [['echec', 'login'], ['echec' => null, 'login' => null, '_controller' => 'App\\Controller\\ConnexionController::index'], [], [['variable', '/', '[^/]++', 'login', true], ['variable', '/', '[^/]++', 'echec', true], ['text', '/connexion']], [], []],
    'seConnecter' => [[], ['_controller' => 'App\\Controller/ConnexionController::seConnecter'], [], [['text', '/seConnecter']], [], []],
    'seDeconnecter' => [[], ['_controller' => 'App\\Controller/ConnexionController::seDeconnecter'], [], [['text', '/']], [], []],
    'consulterFicheFrais' => [[], ['_controller' => 'App\\Controller\\ConsulterFicheFraisController::index'], [], [['text', '/consulter']], [], []],
];
